use_frameworks!

platform :ios, '12.0'

target 'CommentedExperimental_Example' do
  pod 'CommentedExperimental', :path => '../'

  target 'CommentedExperimental_Tests' do
    inherit! :search_paths

    
  end
end
